[package]
name = "ergot_util"
version = "0.1.0"
edition = "2024"

[dependencies]
# messaging/comms
ergot                = { workspace = true }
serde                = { workspace = true }
tokio                = { workspace = true, features = ["time"] }
thiserror            = { workspace = true }
