[package]
name = "camerastreamer-1"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
opencv = { version = "0.96.0", features = ["videoio", "imgcodecs"] }
bytes = { version = "1.10.1" }
anyhow = { version = "1.0.100" }
