[package]
name = "cameraclient-tcp"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.33.0" }
egui = { version = "0.33.0" }
image = { version = "0.25.8" }
tokio = { version = "1.48.0" , features = ["full"]}
anyhow = "1.0.100"
log = "0.4.28"

egui_plot = "0.34.0"